<#
.SYNOPSIS
    Refresh the deterministic site data from source-of-truth.

.DESCRIPTION
    Re-reads:
      - Plugin.cs           ->  plugin version
      - git log             ->  last commit + recent 8 commits
      - current date        ->  lastUpdated

    Re-writes:
      - site/data/sync-status.json   (meta.plugin / lastCommit / lastUpdated)
      - site/data/roadmap.json       (recentCommits)
      - site/badges/coverage.svg     (a tiny static "X% built" SVG badge)
      - STATUS.md                    (a markdown snapshot for README inclusion)
      - README.md                    (between <!-- AUTO:STATUS-BEGIN --> markers)

    Content fields (scenes[*].percent, scenes[*].synced, etc.) are NOT touched.
    Those are human-edited.

    This script is invoked locally AND from .github/workflows/site.yml on push.

.NOTES
    Works on Windows PowerShell 5.1 and PowerShell 7+ (used by Ubuntu runners).
#>

[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".."))
)

$ErrorActionPreference = "Stop"
Set-Location -LiteralPath $RepoRoot

function Read-PluginVersion {
    $pluginCs = "src/WoodburySpectatorSync/Plugin.cs"
    if (-not (Test-Path -LiteralPath $pluginCs)) {
        throw "Plugin.cs not found at $pluginCs"
    }
    $text = Get-Content -LiteralPath $pluginCs -Raw
    if ($text -match '\[BepInPlugin\(\s*"[^"]+"\s*,\s*"[^"]+"\s*,\s*"([^"]+)"\s*\)\]') {
        return $Matches[1]
    }
    throw "Could not extract plugin version from Plugin.cs"
}

function Get-RecentCommits {
    param([int]$Count = 8)
    $raw = git log --pretty=format:"%h%x09%s" -n $Count 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $raw) {
        Write-Warning "git log returned nothing; leaving recentCommits unchanged"
        return $null
    }
    $list = @()
    foreach ($line in $raw -split "`n") {
        $parts = $line -split "`t", 2
        if ($parts.Length -ge 2) {
            $subj = $parts[1].Trim()
            if ($subj.Length -gt 90) { $subj = $subj.Substring(0, 87) + "..." }
            $list += [ordered]@{ sha = $parts[0]; subject = $subj }
        }
    }
    return $list
}

function Read-Json {
    param([string]$Path)
    return Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json
}

function Write-Json {
    param($Object, [string]$Path)
    $json = $Object | ConvertTo-Json -Depth 32
    Set-Content -LiteralPath $Path -Value $json -Encoding UTF8 -NoNewline
    Add-Content -LiteralPath $Path -Value "`n" -Encoding UTF8 -NoNewline
}

function New-CoverageSvg {
    param([int]$Percent, [string]$OutPath)
    $clamped = [Math]::Max(0, [Math]::Min(100, $Percent))
    $color =
        if ($clamped -ge 80) { "#43a047" }
        elseif ($clamped -ge 50) { "#fb8c00" }
        else { "#ef5350" }
    $svg = @"
<svg xmlns="http://www.w3.org/2000/svg" width="124" height="20" role="img" aria-label="coverage: ${clamped}% built">
  <linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#fff" stop-opacity=".15"/><stop offset="1" stop-opacity=".15"/></linearGradient>
  <mask id="m"><rect width="124" height="20" rx="3" fill="#fff"/></mask>
  <g mask="url(#m)">
    <rect width="62" height="20" fill="#1b3a5b"/>
    <rect x="62" width="62" height="20" fill="${color}"/>
    <rect width="124" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="31" y="14">co-op built</text>
    <text x="93" y="14">${clamped}%</text>
  </g>
</svg>
"@
    $parent = Split-Path -Parent $OutPath
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    Set-Content -LiteralPath $OutPath -Value $svg -Encoding UTF8 -NoNewline
}

function New-StatusSnapshot {
    param($Meta, $Scenes, [string]$OutPath)
    $lines = @()
    $lines += "<!-- Auto-generated by scripts/Update-SiteData.ps1 -- do not hand-edit. -->"
    $lines += ""
    $lines += "**Plugin** ``$($Meta.plugin)``  **Wire protocol** ``$($Meta.protocol)``  **Updated** $($Meta.lastUpdated)  **Overall** $($Meta.overallPercent)% built"
    $lines += ""
    $lines += "| Chapter | Status | Coverage |"
    $lines += "| --- | --- | --- |"
    foreach ($s in $Scenes) {
        $filled = [int][Math]::Floor($s.percent / 10)
        if ($filled -lt 0) { $filled = 0 } elseif ($filled -gt 10) { $filled = 10 }
        $bar = (([string][char]9608) * $filled) + (([string][char]9617) * (10 - $filled))
        $lines += "| **$($s.name)** | $($s.status) | ``$bar`` $($s.percent)% |"
    }
    $lines += ""
    $lines += "Full live status, roadmap, and source: see the live site."
    Set-Content -LiteralPath $OutPath -Value ($lines -join "`n") -Encoding UTF8 -NoNewline
    Add-Content -LiteralPath $OutPath -Value "`n" -Encoding UTF8 -NoNewline
}

function Update-ReadmeSnapshot {
    param([string]$ReadmePath, [string]$SnapshotPath, [string]$BadgeRelPath, [string]$LiveUrl)
    if (-not (Test-Path -LiteralPath $ReadmePath)) {
        Write-Warning "$ReadmePath not found; skipping README inject"
        return
    }
    if (-not (Test-Path -LiteralPath $SnapshotPath)) {
        Write-Warning "$SnapshotPath not found; skipping README inject"
        return
    }
    $snapshot = Get-Content -LiteralPath $SnapshotPath -Raw -Encoding UTF8
    $readme   = Get-Content -LiteralPath $ReadmePath   -Raw -Encoding UTF8

    $block = "<!-- AUTO:STATUS-BEGIN -->`n"
    $block += "[![co-op built]($BadgeRelPath)]($LiveUrl) [Live status & roadmap ->]($LiveUrl)`n`n"
    $block += $snapshot.TrimEnd("`r","`n") + "`n"
    $block += "<!-- AUTO:STATUS-END -->"

    if ($readme -match "(?s)<!--\s*AUTO:STATUS-BEGIN\s*-->.*?<!--\s*AUTO:STATUS-END\s*-->") {
        $updated = [Regex]::Replace(
            $readme,
            "(?s)<!--\s*AUTO:STATUS-BEGIN\s*-->.*?<!--\s*AUTO:STATUS-END\s*-->",
            { param($m) $block }
        )
    } else {
        Write-Warning "README markers not found; inserting after first heading"
        $updated = $readme -replace "(?m)^(#\s+.+?)$", "`$1`n`n$block`n"
    }

    if ($updated -ne $readme) {
        Set-Content -LiteralPath $ReadmePath -Value $updated -Encoding UTF8 -NoNewline
    }
}

# ============================================================
#  Drive
# ============================================================

Write-Host "-> Reading plugin version from Plugin.cs..."
$plugin = Read-PluginVersion
Write-Host "   plugin = $plugin"

Write-Host "-> Reading git log..."
$commits = Get-RecentCommits -Count 8
if ($commits -and $commits.Count -gt 0) {
    $latestSha  = $commits[0].sha
    $latestSubj = $commits[0].subject
    $latestLine = "$latestSha `"$latestSubj`""
    Write-Host "   latest = $latestLine"
    Write-Host "   commits = $($commits.Count)"
}

$today = (Get-Date).ToString("yyyy-MM-dd")
Write-Host "   today  = $today"

Write-Host "-> Patching site/data/sync-status.json..."
$syncStatusPath = "site/data/sync-status.json"
$sync = Read-Json -Path $syncStatusPath
$sync.meta.plugin = $plugin
$sync.meta.lastUpdated = $today
if ($commits -and $commits.Count -gt 0) {
    $sync.meta.lastCommit = "$($commits[0].sha) `"$($commits[0].subject)`""
}
Write-Json -Object $sync -Path $syncStatusPath

Write-Host "-> Patching site/data/roadmap.json..."
$roadmapPath = "site/data/roadmap.json"
$roadmap = Read-Json -Path $roadmapPath
if ($commits -and $commits.Count -gt 0) {
    $roadmap.recentCommits = $commits
}
$roadmap.meta.compiled = $today
Write-Json -Object $roadmap -Path $roadmapPath

Write-Host "-> Writing site/badges/coverage.svg..."
$badgePath = "site/badges/coverage.svg"
New-CoverageSvg -Percent ([int]$sync.meta.overallPercent) -OutPath $badgePath

Write-Host "-> Writing STATUS.md snapshot..."
$statusMdPath = "STATUS.md"
New-StatusSnapshot -Meta $sync.meta -Scenes $sync.scenes -OutPath $statusMdPath

Write-Host "-> Updating README.md status block..."
$liveUrl = "https://tudorek12345.github.io/fears-to-fathom-woodbury-getaway-mp-mod/"
Update-ReadmeSnapshot -ReadmePath "README.md" -SnapshotPath $statusMdPath -BadgeRelPath "site/badges/coverage.svg" -LiveUrl $liveUrl

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "  Updated: $syncStatusPath, $roadmapPath, $badgePath, $statusMdPath, README.md"
